
export const metadata = {
  title: "Blood donation system",
  description: "Generated by Hello_world",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      </body>
    </html>
  );
}
